pipeline{

    environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/Cellar/maven/3.9.16/libexec/bin:${env.PATH}"
    }
    agent any
    stages {
        stage('Checkout code') {
            steps {
                git 'https://github.com/shivrajak270/Bloomdev.git'
            }
        }
        stage('Build') {
            steps {
                dir('full-stack-project/bloom/Backend/Backend') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
    }
}