pipeline{
    agent any
    stages {
        stage('Checkout code') {
            steps {
                git 'https://github.com/shivrajak270/Bloomdev.git'
            }
        }
        stage('Build') {
            steps {
                dir('full-stack-project/bloom/Backend/Backend') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
    }
}