pipeline{
    agent any
     environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/Cellar/maven/3.9.16/libexec/bin:${env.PATH}"
    }
    stages {
        stage('Checkout code') {
            steps {
                        git branch: 'main',
                        url: 'https://github.com/shivrajak270/Bloomdev.git'
            }
        }
        stage('Build') {
            steps {
                dir('full-stack-project/bloom/Backend/Backend') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Deploy to vm'){
            steps{
                sshagent(credentials: ['vm-ssh-key']){
                    dir('full-stack-project/bloom/Backend/Backend') {
                        sh '''
                        scp target/demo-0.0.1-SNAPSHOT.jar shivraj@192.168.64.5:/home/shivraj/demo-0.0.1-SNAPSHOT.jar
                           '''
                    }

                }

            }
        }
        stage('Stop Old Application') {
            steps {

                sshagent(credentials: ['vm-ssh-key']) {

                    sh '''
            ssh shivraj@192.168.64.5 "
                pkill -f demo-0.0.1-SNAPSHOT.jar || true
            "
            '''

                }
            }
        }
        stage('Start New Application') {
            steps {

                sshagent(credentials: ['vm-ssh-key']) {

                    sh '''
            ssh shivraj@192.168.64.5 "
                nohup java -jar /home/shivraj/demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            "
            '''

                }
            }
        }
    }
}
