spring.application.name=notification
server.port=8082
#xxww usiq ykxz pucp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivrajak280@gmail.com
spring.mail.password=xxwwusiqykxzpucp

spring.data.redis.host= redis-10160.c92.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=10160

consumer.name=consumer-1

#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.password=mz4S5tID7TCrV7N7jXggLI3gGkVoMcoJ

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#logging.level.org.springframework.data.redis=DEBUG
#logging.level.io.lettuce.core=DEBUG
#logging.level.org.springframework.boot.autoconfigure.data.redis=DEBUG

logging.level.org.springframework.data.redis=INFO
logging.level.io.lettuce.core=INFO
logging.level.org.springframework=INFO